spring:
  # Kafka 配置项，对应 KafkaProperties 配置类
  kafka:
    bootstrap-servers: 127.0.0.1:9092 # 指定 Kafka Broker 地址，可以设置多个，以逗号分隔
    # Kafka Producer 配置项
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 消息的 key 的序列化
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # 消息的 value 的序列化
    # Kafka Consumer 配置项
    consumer:
      group-id: artificial-general-intelligence-group # 消费者组 ID
      auto-offset-reset: earliest # 消费者消费消息时，从最早的消息开始消费
      enable-auto-commit: true # 消费者消费消息时，自动提交偏移量
      auto-commit-interval: 1000 # 消费者消费消息时，自动提交偏移量的间隔时间
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.jzjr.kafkademo.message #消费者在处理在处理json格式的消息时，对于反序列化过程中要信任的包

logging:
  level:
    org:
      springframework:
        kafka: INFO # spring-kafka INFO 日志太多了，所以我们限制只打印 ERROR 级别
      apache:
        kafka: INFO # kafka INFO 日志太多了，所以我们限制只打印 ERROR 级别

agi:
  topic: artificial-general-intelligence
